#!/usr/bin/env bash

HOURS=$1

if [ -z $HOURS ]; then
  echo "Usage: $0 <num hours>"
  HOURS="2"
  echo "Defaulting to $HOURS hours"
fi

echo "Adding key for $HOURS hours"

ssh-add -t ${HOURS}H $(dirname $0)/id_rsa
osascript -e 'tell application "Finder" to eject "secrets"'
